### ISSUE TITLE
exporter for blender 4.1 is not working.

### ISSUE THREAD

**Issue by nerondes** [lsalzman/iqm#65]
Exporter for blender 4.1 is not working. I had this problem with a different plugin. I think there were changes in this structure in 4.1 unlike 4.0. Some old plugins are not working. Do you plan to update it? 

This is what I read on the blender side about the subject. 
https://developer.blender.org/docs/release_notes/4.1/python_api/#mesh

Thanks in advance.
------------------------------------------------------------------------------------------

Python: Traceback (most recent call last):
  File "C:\Users\xxxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\iqm_export.py", line 1136, in execute
    exportIQM(context, self.properties.filepath, self.properties.usemesh, self.properties.usemods, self.properties.useskel, self.properties.usebbox, self.properties.usecol, self.properties.usescale, self.properties.animspec, matfun, self.properties.derigify, self.properties.boneorder, self.properties.namedmaterialmeshes)
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\iqm_export.py", line 1072, in exportIQM
    meshes = collectMeshes(context, bones, scale, matfun, useskel, usecol, usemods, filetype, namedmaterialmeshes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\iqm_export.py", line 825, in collectMeshes
    data.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'calc_normals_split'

**Comment by lsalzman** [comment]
I am kind of out of the loop with recent Blender versions. Do you want to investigate how the script needs to be modified to work with 4.1?

**Comment by lsalzman** [comment]
It seems like if the offending call is removed from the script, it might just work. Is that so?

**Comment by Rev3n4nt** [comment]
Accidentally updated Blender to 4.1 on Linux and plugin does not work anymore

**Comment by Xury46** [comment]
> It seems like if the offending call is removed from the script, it might just work. Is that so?

I just gave this a shot, and indeed that works.
I cloned the repo and made a branch for this, if you give me access I can make a pull request :)

**Comment by lsalzman** [comment]
I committed an initial version of the 4.1 exporter that just removes that call. I was just waiting for someone to confirm whether that worked or not. In any case, let's just keep trialing this and if there are further problems we can address them as they come along.

**Comment by Xury46** [comment]
Wow, thank you for the quick turn around! That's really exciting. Now that the GZDoom engine supports IQM I imagine this exporter will be even more popular than it was before, so keeping it working is greatly appreciated.

**Comment by MajorCooke** [comment]
This bug is still happening.

**Comment by MajorCooke** [comment]
Unfortunately, at of Blender 4.3.2, this issue has come up again. No idea what to make of it.

**Comment by toybonnie1** [comment]
The add-on continue don't working in blender 4.1, when I install it shows that error mentioned and do't shows up the option to activate the add-on

**Comment by lsalzman** [comment]
> The add-on continue don't working in blender 4.1, when I install it shows that error mentioned and do't shows up the option to activate the add-on

There is no more call to calc_normals_split in the current exporter in git. So if you are using the correct 4.1 exporter version, this shouldn't be possible. Unless the error is something else and you are mistaken that calc_normals_split is the reason?

**Comment by toybonnie1** [comment]
Yes, is the correct version of the exporter, but I don't know why it don't shows up in the options to active add-ons and literraly I just need to export to finish my project, is all animated and sculpted, only needs to export
